version: '3.8'

services:
  sector-db:
    container_name: postgres-sector
    image: postgres:14.1
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sector

  backend-service:
    container_name: backend-service
    build: task-backend/
    ports:
      - "8080:8080"
    depends_on:
      - sector-db

  fronted-service:
    container_name: fronted-service
    build: task-frontend/
    ports:
      - "4200:4200"
    depends_on:
      - backend-service