INSERT INTO sectors (id, name)
VALUES ('1','Manufacturing'),
      ('2','Other'),
      ('3','Service');

INSERT INTO sectors (id, name, parent_id)
VALUES ('4','Construction materials','1'),
       ('5','Electronics and Optics','1'),
       ('6','Food and Beverage','1'),
       ('7','Furniture','1'),
       ('8','Machinery','1'),
       ('9','Metalworking','1'),
       ('10','Plastic and Rubber','1'),
       ('11','Printing','1'),
       ('12','Textile and Clothing','1'),
       ('13','Wood','1'),
       ('14','Creative industries','2'),
       ('15','Energy technology','2'),
       ('16','Environment','2'),
       ('17','Business services','3'),
       ('18','Engineering','3'),
       ('19','Information Technology and Telecommunications','3'),
       ('20','Tourism','3'),
       ('21','Translation services','3'),
       ('22','Transport and Logistics','3');

INSERT INTO sectors (id, name, parent_id)
VALUES ('23','Bakery & confectionery products','6'),
       ('24','Beverages','6'),
       ('25','Fish & fish products','6'),
       ('26','Meat & meat products','6'),
       ('27','Milk & dairy products','6'),
       ('28','Other','6'),
       ('29','Sweet & snack food','6'),
       ('30','Bathroom/sauna','7'),
       ('31','Bedroom','7'),
       ('32','Children''s room','7'),
       ('33','Kitchen','7'),
       ('34','Living room','7'),
       ('35','Office','7'),
       ('36','Other (Furniture)','7'),
       ('37','Outdoor','7'),
       ('38','Project furniture','7'),
       ('39','Machinery components','8'),
       ('40','Machinery equipment/tools','8'),
       ('41','Manufacture of machinery','8'),
       ('42','Maritime','8'),
       ('43','Metal structures','8'),
       ('44','Other','8'),
       ('45','Repair and maintenance service','8'),
       ('46','Construction of metal structures','9'),
       ('47','Houses and buildings','9'),
       ('48','Metal products','9'),
       ('49','Metal works','9'),
       ('50','Packaging','10'),
       ('51','Plastic goods','10'),
       ('52','Plastic processing technology','10'),
       ('53','Plastic profiles','10'),
       ('54','Advertising','11'),
       ('55','Book/Periodicals printing','11'),
       ('56','Labelling and packaging printing','11'),
       ('57','Clothing','12'),
       ('58','Textile','12'),
       ('59','Other (Wood)','13'),
       ('60','Wooden building materials','13'),
       ('61','Wooden houses','13'),
       ('62','Data processing, Web portals, E-marketing','19'),
       ('63','Programming, Consultancy','19'),
       ('64','Software, Hardware','19'),
       ('65','Telecommunications','19'),
       ('66','Air','22'),
       ('67','Rail','22'),
       ('68','Road','22'),
       ('69','Water','22');

INSERT INTO sectors (id, name, parent_id)
VALUES ('70','Aluminium and steel workboats','42'),
       ('71','Boat/Yacht building','42'),
       ('72','Ship repair and conversion','42'),
       ('73','CNC-machining','49'),
       ('74','Forgings, Fasteners','49'),
       ('75','Gas, Plasma, Laser cutting','49'),
       ('76','MIG, TIG, Aluminum welding','49'),
       ('77','Blowing','52'),
       ('78','Moulding','52'),
       ('79','Plastics welding and processing','52');